// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prkromoacxwfowdjnvsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBya3JvbW9hY3h3Zm93ZGpudnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDg2NDksImV4cCI6MjA2MDgyNDY0OX0.-N-a-s3h45IL4qAVFhYoVqbHeXtcXsj_KwlfU0TBsCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);